# Generated by Django 4.2.2 on 2023-07-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=10)),
                ('author_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
