# Generated by Django 4.2.1 on 2023-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_employee_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
