# Generated by Django 4.2.1 on 2023-06-06 17:19

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pet_image',
            field=models.ImageField(upload_to='', validators=[Petstagram.photos.validators.image_size_validator_5mb]),
        ),
    ]
