# Generated by Django 4.2.2 on 2023-06-11 12:35

from django.db import migrations, models
import exam_prep_2.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[exam_prep_2.web.models.validate_username], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[exam_prep_2.web.models.validate_username], verbose_name='Last Name'),
        ),
    ]
